export const posts = [
  {
    slug: "1",
    id: "1",
    name: "The Audacious Project reveals its 2024 cohort",
    description: "The Audacious Project reveals its 2024 cohort",
    author: "TED Staff",
    urlImage: "/images/picture_1.webp",
    createAt: "9:00",
  },
  {
    slug: "3",
    id: "3",
    name: "The Audacious Project reveals its 2024 cohort",
    description: "The Audacious Project reveals its 2024 cohort",
    author: "TED Staff",
    urlImage: "/images/picture_1.webp",
    createAt: "9:00",
  },
  {
    slug: "3",
    id: "3",
    name: "The Audacious Project reveals its 2024 cohort",
    description: "The Audacious Project reveals its 2024 cohort",
    author: "TED Staff",
    urlImage: "/images/picture_1.webp",
    createAt: "9:00",
  },
  {
    slug: "4",
    id: "4",
    name: "The Audacious Project reveals its 2024 cohort",
    description: "The Audacious Project reveals its 2024 cohort",
    author: "TED Staff",
    urlImage: "/images/picture_1.webp",
    createAt: "9:00",
  },
  {
    slug: "5",
    id: "5",
    name: "The Audacious Project reveals its 2024 cohort",
    description: "The Audacious Project reveals its 2024 cohort",
    author: "TED Staff",
    urlImage: "/images/picture_1.webp",
    createAt: "9:00",
  },
];
